import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";

import { TokenProvider } from "@/lib/contexts/token";
import { UserProvider } from "@/lib/contexts/user";
import { Toaster } from "sonner";

import { DarkModeProvider } from "@/lib/contexts/darkmode";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "IOD Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DarkModeProvider>
          <TokenProvider>
            <UserProvider>
              <div className="flex h-screen w-screen flex-col">{children}</div>
            </UserProvider>
          </TokenProvider>
          <Toaster richColors />
        </DarkModeProvider>
      </body>
    </html>
  );
}
